INSERT INTO brands 
(title, slug, status, created_at, updated_at) VALUES 
('CROUSE HINDS ECM','crouse-hinds-ecm','active',NOW(),NOW()),
('AMETEK Land instruments','ametek-land-instruments','active',NOW(),NOW()),
('Drer','drer','active',NOW(),NOW()),
('ESMIL WATER SYSTEMS','esmil-water-systems','active',NOW(),NOW()),
('Mcmaster','mcmaster','active',NOW(),NOW()),
('SCHNEIDER ELECTRIC SA','schneider-electric-sa','active',NOW(),NOW()),
('FERRAZ SHAWMUT','ferraz-shawmut','active',NOW(),NOW()),
('6A672','6a672','active',NOW(),NOW()),
('CHICOA4','chicoa4','active',NOW(),NOW()),
('ThermoSceintific','thermosceintific','active',NOW(),NOW()),
('INVENSYS','invensys','active',NOW(),NOW()),
('Notifier, By Honeywell','notifier-by-honeywell','active',NOW(),NOW()),
('DRAEGER SAFETY INC','draeger-safety-inc','active',NOW(),NOW()),
('DELTA CONTROLS LTD GB','delta-controls-ltd-gb','active',NOW(),NOW()),
('SPX PROCESS EQUIPMENT','spx-process-equipment','active',NOW(),NOW()),
('Interactive Safety Products, Inc','interactive-safety-products-inc','active',NOW(),NOW()),
('GENERAL ELECTRIC','general-electric','active',NOW(),NOW()),
('AMETEK Lands instruments','ametek-lands-instruments','active',NOW(),NOW()),
('FF-44200-05','ff-44200-05','active',NOW(),NOW()),
('Drger','drger','active',NOW(),NOW()),
('TP Solutions (Thermal Packaging Solutions)','tp-solutions-thermal-packaging-solutions','active',NOW(),NOW()),
('TPS2024B','tps2024b','active',NOW(),NOW()),
('Mountz','mountz','active',NOW(),NOW()),
('C.I ANALYTICS','c-i-analytics','active',NOW(),NOW()),
('PS62.DXEAL2HDMAX','ps62-dxeal2hdmax','active',NOW(),NOW()),
('AV-950R-20','av-950r-20','active',NOW(),NOW()),
('AV-950T-20','av-950t-20','active',NOW(),NOW()),
('ASCO','asco','active',NOW(),NOW()),
('11A5326X132','11a5326x132','active',NOW(),NOW()),
('GE23311X0A2','ge23311x0a2','active',NOW(),NOW()),
('Thyro-PX 2PX 500- 495 HF','thyro-px-2px-500-495-hf','active',NOW(),NOW()),
('TYCO','tyco','active',NOW(),NOW()),
('ECKARDT INVENSYS (SCHNEIDER ELECTRIC)','eckardt-invensys-schneider-electric','active',NOW(),NOW()),
('Wrtsil Water Systems Ltd','wrtsil-water-systems-ltd','active',NOW(),NOW()),
('2K378314042','2k378314042','active',NOW(),NOW()),
('SCHNEIDER ELECTRIC','schneider-electric','active',NOW(),NOW()),
('GTC ITALIA SRL/KTM VALVES','gtc-italia-srl-ktm-valves','active',NOW(),NOW()),
('TYCO VALVES AND CONTROLSAB DISTRIBUTION','tyco-valves-and-controlsab-distribution','active',NOW(),NOW()),
('CROUSE HINDS ECM USCOOPER INDUSTRIES INCORPORATED','crouse-hinds-ecm-uscooper-industries-incorporated','active',NOW(),NOW()),
('CORTEM SPA','cortem-spa','active',NOW(),NOW()),
('SANDVIK SECO','sandvik-seco','active',NOW(),NOW()),
('Emerson Fisher (BAUMANN-FISHER CONTROLS INT\'L)','emerson-fisher-baumann-fisher-controls-int-l','active',NOW(),NOW()),
('Sioux','sioux','active',NOW(),NOW()),
('APPARATEBAU SCHWEISSTECHNIK GMBH','apparatebau-schweisstechnik-gmbh','active',NOW(),NOW()),
('Plasser UK Limited','plasser-uk-limited','active',NOW(),NOW()),
('IV5060','iv5060','active',NOW(),NOW()),
('Mampaey','mampaey','active',NOW(),NOW()),
('Azcue Pump','azcue-pump','active',NOW(),NOW()),
('VULCANIC UK','vulcanic-uk','active',NOW(),NOW()),
('Alfa','alfa','active',NOW(),NOW()),
('Alco','alco','active',NOW(),NOW()),
('SAFT','saft','active',NOW(),NOW()),
('420 744 501 2 23','420-744-501-2-23','active',NOW(),NOW()),
('New','new','active',NOW(),NOW()),
('D663Z327K P03JOMD6VSB0','d663z327k-p03jomd6vsb0','active',NOW(),NOW()),
('NU-1032 P&ID','nu-1032-p-id','active',NOW(),NOW()),
('LC1D09BD','lc1d09bd','active',NOW(),NOW()),
('141-206','141-206','active',NOW(),NOW()),
('H0012-5','h0012-5','active',NOW(),NOW()),
('PHOTRON LAMPS / DELTA SCIENTIFIC','photron-lamps-delta-scientific','active',NOW(),NOW()),
('roxon','roxon','active',NOW(),NOW()),
('Alco  XB','alco-xb','active',NOW(),NOW()),
('AMETEK','ametek','active',NOW(),NOW()),
('Funke Wrmeaustauscher GmbH','funke-wrmeaustauscher-gmbh','active',NOW(),NOW()),
('Productos Plasticos Anticorrosivos','productos-plasticos-anticorrosivos','active',NOW(),NOW()),
('MAB SA','mab-sa','active',NOW(),NOW()),
('MAB MASCHINEN APPARATE BAU SA.','mab-maschinen-apparate-bau-sa','active',NOW(),NOW()),
('EMERSON','emerson','active',NOW(),NOW()),
('Keysight','keysight','active',NOW(),NOW()),
('FIAMMS','fiamms','active',NOW(),NOW()),
('MERCK MILLIPORE','merck-millipore','active',NOW(),NOW()),
('GUTOR ELECTRONICS LCC','gutor-electronics-lcc','active',NOW(),NOW()),
('Simco Engineers','simco-engineers','active',NOW(),NOW()),
('SAAB ROSEMOUNT TANK CONTROL','saab-rosemount-tank-control','active',NOW(),NOW()),
('SIGMA-ALDRICH.','sigma-aldrich','active',NOW(),NOW()),
('merck','merck','active',NOW(),NOW()),
('FIAMM SPA, ITALY','fiamm-spa-italy','active',NOW(),NOW()),
('REXROTH','rexroth','active',NOW(),NOW()),
('FIAMM','fiamm','active',NOW(),NOW()),
('M. COULTHARD & CO., LTD.','m-coulthard-co-ltd','active',NOW(),NOW()),
('SAAB ROSEMOUNT TANK GAUGING LTD','saab-rosemount-tank-gauging-ltd','active',NOW(),NOW()),
('AA TECHNISCHE DIENSTEAB SICHERHEIT UND','aa-technische-diensteab-sicherheit-und','active',NOW(),NOW()),
('SEW','sew','active',NOW(),NOW()),
('EMERSON-ROSEMOUNT','emerson-rosemount','active',NOW(),NOW()),
('EMERSON ROSEMOUNT','emerson-rosemount','active',NOW(),NOW()),
('ARBURG GMBH & CO','arburg-gmbh-co','active',NOW(),NOW()),
('Shrack (Autolift)','shrack-autolift','active',NOW(),NOW()),
('VIKOMA INTERNATIONAL LTD GB','vikoma-international-ltd-gb','active',NOW(),NOW()),
('GEA','gea','active',NOW(),NOW()),
('SCHRACK AUSTRIA GMBH','schrack-austria-gmbh','active',NOW(),NOW()),
('FG WILSON EQUIPMENT','fg-wilson-equipment','active',NOW(),NOW()),
('PARAGON SCIENTIFIC LTDDATASHEET ATTACHED','paragon-scientific-ltddatasheet-attached','active',NOW(),NOW()),
('MOTOR, 5HP, HIGH PRESSURE STREAM WASHER','motor-5hp-high-pressure-stream-washer','active',NOW(),NOW()),
('PUMP, PLUNGER, HIGH PRESSURE STREAM WASHER','pump-plunger-high-pressure-stream-washer','active',NOW(),NOW()),
('PHILIPS','philips','active',NOW(),NOW()),
('PAC','pac','active',NOW(),NOW()),
('Mitutoyo - Japan Surftest_SJ210','mitutoyo-japan-surftest-sj210','active',NOW(),NOW()),
('Unipart rail','unipart-rail','active',NOW(),NOW()),
('Metrohm iConnect','metrohm-iconnect','active',NOW(),NOW()),
('APT SECURITY SYSTEM','apt-security-system','active',NOW(),NOW()),
('Rosemount','rosemount','active',NOW(),NOW()),
('SANDVIK','sandvik','active',NOW(),NOW()),
('AJ KOELLEMANN','aj-koellemann','active',NOW(),NOW()),
('KINETROL LTD.','kinetrol-ltd','active',NOW(),NOW()),
('GEA Mechanical Equipment UK Ltd','gea-mechanical-equipment-uk-ltd','active',NOW(),NOW()),
('GEA WESTFALIA','gea-westfalia','active',NOW(),NOW()),
('PREMABERGO ITALIANA SR','premabergo-italiana-sr','active',NOW(),NOW()),
('KABA GALLENSCHUTZ GMBH','kaba-gallenschutz-gmbh','active',NOW(),NOW()),
('SCHMALZ GMBH','schmalz-gmbh','active',NOW(),NOW()),
('SIEMENS AG','siemens-ag','active',NOW(),NOW()),
('INDUSTRIAL CLUTCH PARTS /WESTCAR','industrial-clutch-parts-westcar','active',NOW(),NOW()),
('Schrack Technik','schrack-technik','active',NOW(),NOW()),
('BIS PROZESSTECHNIK','bis-prozesstechnik','active',NOW(),NOW()),
('COPERION','coperion','active',NOW(),NOW()),
('READY OILFIELD SAFETY & SERVICESPTE LTD','ready-oilfield-safety-servicespte-ltd','active',NOW(),NOW()),
('GATES','gates','active',NOW(),NOW()),
('Balluff','balluff','active',NOW(),NOW()),
('CONDOR','condor','active',NOW(),NOW()),
('RELIABLE AUTOMATIC SPRINKLER CO. INC','reliable-automatic-sprinkler-co-inc','active',NOW(),NOW()),
('G.M.P SPA','g-m-p-spa','active',NOW(),NOW()),
('ROBUSCHI','robuschi','active',NOW(),NOW()),
('Z ELECTROMECANICAS ARA SAZ','z-electromecanicas-ara-saz','active',NOW(),NOW()),
('Honeywell','honeywell','active',NOW(),NOW()),
('ICE- INTERNATIONAL COMBUSTION EQUIPMENT','ice-international-combustion-equipment','active',NOW(),NOW()),
('PRODUCTOS PLASTICOS','productos-plasticos','active',NOW(),NOW()),
('JANSENS & DIEPERINK','jansens-dieperink','active',NOW(),NOW()),
('EATON - CUTLER HAMMER','eaton-cutler-hammer','active',NOW(),NOW()),
('DE IULIIS MACCHINE SPA','de-iuliis-macchine-spa','active',NOW(),NOW()),
('Hach','hach','active',NOW(),NOW()),
('BARKSDALE CONTROL PRODUCTS','barksdale-control-products','active',NOW(),NOW()),
('ATEC','atec','active',NOW(),NOW()),
('CRYOSTAR SAS','cryostar-sas','active',NOW(),NOW()),
('MHCVBN2','mhcvbn2','active',NOW(),NOW()),
('Fashion Manufacturer','fashion-manufacturer','active',NOW(),NOW()),
('Werma','werma','active',NOW(),NOW()),
('KENNAMETAL','kennametal','active',NOW(),NOW()),
('McWane International','mcwane-international','active',NOW(),NOW()),
('RAPIDROP GLOBAL LTD','rapidrop-global-ltd','active',NOW(),NOW()),
('FILTRATION GROUP (FORMERLY MAHLE)','filtration-group-formerly-mahle','active',NOW(),NOW()),
('HBE','hbe','active',NOW(),NOW()),
('MEANWELL','meanwell','active',NOW(),NOW()),
('MTM POWER GMBH','mtm-power-gmbh','active',NOW(),NOW()),
('Kennedy Valve','kennedy-valve','active',NOW(),NOW()),
('Pneumax','pneumax','active',NOW(),NOW()),
('Intza','intza','active',NOW(),NOW()),
('ROTORK/CENTORK','rotork-centork','active',NOW(),NOW()),
('Greenbrier (GBRX)','greenbrier-gbrx','active',NOW(),NOW()),
('CREATE','create','active',NOW(),NOW()),
('STILL','still','active',NOW(),NOW()),
('KABEL SCHLEPP','kabel-schlepp','active',NOW(),NOW()),
('HP','hp','active',NOW(),NOW()),
('Shrack','shrack','active',NOW(),NOW()),
('FLEXOTECH','flexotech','active',NOW(),NOW()),
('\"VIKOMA INTERNATIONAL LTD GB \"','vikoma-international-ltd-gb','active',NOW(),NOW()),
('SENINI TECNOSIDERURGICA S.R.L.','senini-tecnosiderurgica-s-r-l','active',NOW(),NOW()),
('CARRARA','carrara','active',NOW(),NOW()),
('DOUGLAS CHERO SPA','douglas-chero-spa','active',NOW(),NOW()),
('CUMMINS','cummins','active',NOW(),NOW()),
('OMB VALVES SPA','omb-valves-spa','active',NOW(),NOW()),
('MURPHY BY ENOVATION CONTROL','murphy-by-enovation-control','active',NOW(),NOW()),
('EXHEAT PTE LTD.','exheat-pte-ltd','active',NOW(),NOW()),
('CONTROL & APPLICATIONS ASIA LTD','control-applications-asia-ltd','active',NOW(),NOW()),
('FG WILSON','fg-wilson','active',NOW(),NOW()),
('PARAGON SCIENTIFIC LTDDATASHEET ATTACHED','paragon-scientific-ltddatasheet-attached','active',NOW(),NOW()),
('AERZEN MASCHINENFABRIK GMBH','aerzen-maschinenfabrik-gmbh','active',NOW(),NOW()),
('SIMCO ENGINEERS JARROW UK','simco-engineers-jarrow-uk','active',NOW(),NOW()),
('UNITED ELECTRIC CONTROLS','united-electric-controls','active',NOW(),NOW()),
('TELEMECANIQUE','telemecanique','active',NOW(),NOW()),
('WORKSMAN TRADING CORPORATION','worksman-trading-corporation','active',NOW(),NOW()),
('NICOTRA Gebhardt','nicotra-gebhardt','active',NOW(),NOW()),
('SERVO NIDEC LLC','servo-nidec-llc','active',NOW(),NOW()),
('FAS SPA','fas-spa','active',NOW(),NOW()),
('Simplex','simplex','active',NOW(),NOW()),
('SAMSON CONTROLS FZE','samson-controls-fze','active',NOW(),NOW()),
('EUROTECH GMBH','eurotech-gmbh','active',NOW(),NOW()),
('VEAB Italia','veab-italia','active',NOW(),NOW()),
('COMEM','comem','active',NOW(),NOW()),
('FIP Spa in Italy','fip-spa-in-italy','active',NOW(),NOW()),
('AMERICAN FLOW CONTROL','american-flow-control','active',NOW(),NOW()),
('AIR PRODUCTS PLC','air-products-plc','active',NOW(),NOW()),
('ABBMa','abbma','active',NOW(),NOW()),
('DAYTON PHOENIX GROUP','dayton-phoenix-group','active',NOW(),NOW()),
('BIS PROZESSTECHNIK / BILFINGER','bis-prozesstechnik-bilfinger','active',NOW(),NOW()),
('Arburg','arburg','active',NOW(),NOW()),
('BESTOBELL STEAM','bestobell-steam','active',NOW(),NOW()),
('CMC','cmc','active',NOW(),NOW()),
('MHT TECHNOLOGY LTD','mht-technology-ltd','active',NOW(),NOW()),
('Samia Italia Sr','samia-italia-sr','active',NOW(),NOW()),
('DETCON','detcon','active',NOW(),NOW()),
('VAL-MATIC','val-matic','active',NOW(),NOW()),
('ORBITEC SA','orbitec-sa','active',NOW(),NOW()),
('ALLWEILER AG','allweiler-ag','active',NOW(),NOW()),
('KRAMER ELECTRONICS, LTD.','kramer-electronics-ltd','active',NOW(),NOW()),
('ALLGAIER WERKE GMBH','allgaier-werke-gmbh','active',NOW(),NOW()),
('BOSCH REXROTH','bosch-rexroth','active',NOW(),NOW()),
('PharmaSafe','pharmasafe','active',NOW(),NOW()),
('CRANE ENERGY FLOW SOLUTIONS','crane-energy-flow-solutions','active',NOW(),NOW()),
('\"INDUSTRIAL CLUTCH PARTS / WESTCAR\"','industrial-clutch-parts-westcar','active',NOW(),NOW()),
('FAAM','faam','active',NOW(),NOW()),
('AIR CONTROL INDUSTRIES','air-control-industries','active',NOW(),NOW()),
('LGC STANDARDS VHG LABS','lgc-standards-vhg-labs','active',NOW(),NOW()),
('J. SCHMALZ GMBH','j-schmalz-gmbh','active',NOW(),NOW()),
('ZAMIL AIR CONDITIONER','zamil-air-conditioner','active',NOW(),NOW()),
('\"COPERION \"','coperion','active',NOW(),NOW()),
('ALCAD','alcad','active',NOW(),NOW()),
('ANDRITZ','andritz','active',NOW(),NOW()),
('Fosse Liquitrol, Teknomelt','fosse-liquitrol-teknomelt','active',NOW(),NOW()),
('BRENNAN','brennan','active',NOW(),NOW()),
('ESME LTD','esme-ltd','active',NOW(),NOW()),
('EMERSON - ASCO','emerson-asco','active',NOW(),NOW()),
('Euchner','euchner','active',NOW(),NOW()),
('VS Lighting Datasheet attached','vs-lighting-datasheet-attached','active',NOW(),NOW()),
('CHECKPOINT','checkpoint','active',NOW(),NOW()),
('DIXON','dixon','active',NOW(),NOW()),
('ADLER S.P.A','adler-s-p-a','active',NOW(),NOW()),
('LEUZE ELECTRONC','leuze-electronc','active',NOW(),NOW()),
('NEPTRONIC','neptronic','active',NOW(),NOW()),
('CERATIZIT','ceratizit','active',NOW(),NOW()),
('Mitutoyo','mitutoyo','active',NOW(),NOW()),
('FLUID SYSTEM S.L.','fluid-system-s-l','active',NOW(),NOW()),
('SPEEDAIRE','speedaire','active',NOW(),NOW()),
('EQUIREPSA','equirepsa','active',NOW(),NOW()),
('RELIABLE AUTOMATIC SPRINKLER CO. INC.','reliable-automatic-sprinkler-co-inc','active',NOW(),NOW()),
('HASCON ENGG SPA','hascon-engg-spa','active',NOW(),NOW()),
('LOMBARBDINI','lombarbdini','active',NOW(),NOW()),
('G.M.P.SPA','g-m-p-spa','active',NOW(),NOW()),
('DRESSER-RAND COMPANY LTD','dresser-rand-company-ltd','active',NOW(),NOW()),
('WATEROUS CO.','waterous-co','active',NOW(),NOW()),
('NUOVA ASP SRL','nuova-asp-srl','active',NOW(),NOW()),
('HASCON ENGINEERING SPA','hascon-engineering-spa','active',NOW(),NOW()),
('Z ELECTROMECANICAS ARA SA','z-electromecanicas-ara-sa','active',NOW(),NOW()),
('ICE- INTERNATIONAL COMBUSTION','ice-international-combustion','active',NOW(),NOW()),
('COOLER SERVICE CO INC','cooler-service-co-inc','active',NOW(),NOW()),
('RELIABLE USA','reliable-usa','active',NOW(),NOW()),
('Liebert','liebert','active',NOW(),NOW()),
('ICM','icm','active',NOW(),NOW()),
('Flexotech','flexotech','active',NOW(),NOW()),
('BARKSDALE','barksdale','active',NOW(),NOW()),
('FAGGIOLATI PUMPS SPA','faggiolati-pumps-spa','active',NOW(),NOW()),
('CRYOSTAR','cryostar','active',NOW(),NOW()),
('Corrpro','corrpro','active',NOW(),NOW()),
('Printronix','printronix','active',NOW(),NOW()),
('Maxnovo srl','maxnovo-srl','active',NOW(),NOW()),
('BECKHOFF','beckhoff','active',NOW(),NOW()),
('BRINKMANN','brinkmann','active',NOW(),NOW()),
('Frigosystem','frigosystem','active',NOW(),NOW()),
('AS-PL','as-pl','active',NOW(),NOW()),
('JENNY','jenny','active',NOW(),NOW()),
('SCHRACK','schrack','active',NOW(),NOW()),
('NORGREN','norgren','active',NOW(),NOW()),
('METROHM','metrohm','active',NOW(),NOW()),
('Zenex','zenex','active',NOW(),NOW()),
('GRUNDFOS.','grundfos','active',NOW(),NOW()),
('MILT-ROY','milt-roy','active',NOW(),NOW()),
('Mc Miller','mc-miller','active',NOW(),NOW()),
('Rickmeier GmbH','rickmeier-gmbh','active',NOW(),NOW()),
('CLASSIC','classic','active',NOW(),NOW()),
('HEAT TRANSFER SYSTEMS','heat-transfer-systems','active',NOW(),NOW()),
('IFM ELECTRONICS GMBHOCM','ifm-electronics-gmbhocm','active',NOW(),NOW()),
('GMBH','gmbh','active',NOW(),NOW()),
('PRYSMIAN CABLES AND SYSTEMS','prysmian-cables-and-systems','active',NOW(),NOW()),
('GEA WESTFALIA SEPARATOR','gea-westfalia-separator','active',NOW(),NOW()),
('SAUDI TECHNICAL SUPPLY CO. LTD','saudi-technical-supply-co-ltd','active',NOW(),NOW()),
('NEW YORK AIR BRAKE','new-york-air-brake','active',NOW(),NOW()),
('APH','aph','active',NOW(),NOW()),
('PCD','pcd','active',NOW(),NOW()),
('READY OILFIELD SAFETY & SERVICES PTE LTD','ready-oilfield-safety-services-pte-ltd','active',NOW(),NOW()),
('NORGREN HERION','norgren-herion','active',NOW(),NOW()),
('Timken','timken','active',NOW(),NOW()),
('M-D Pneumatics','m-d-pneumatics','active',NOW(),NOW()),
('ATOS','atos','active',NOW(),NOW()),
('ROBUSCHI SPA','robuschi-spa','active',NOW(),NOW()),
('Unipart','unipart','active',NOW(),NOW()),
('EMD','emd','active',NOW(),NOW()),
('INTERCAT','intercat','active',NOW(),NOW()),
('Gardner Denver Compair Reavell','gardner-denver-compair-reavell','active',NOW(),NOW()),
('Dayton-Phoenix Group','dayton-phoenix-group','active',NOW(),NOW()),
('ALSTOM','alstom','active',NOW(),NOW()),
('Fleetguard','fleetguard','active',NOW(),NOW()),
('DUETZ','duetz','active',NOW(),NOW()),
('CZECH REPUBLIC','czech-republic','active',NOW(),NOW()),
('Corema','corema','active',NOW(),NOW()),
('Photon Meissener Technologies','photon-meissener-technologies','active',NOW(),NOW()),
('ABLEREX','ablerex','active',NOW(),NOW()),
('ANDEROL','anderol','active',NOW(),NOW()),
('ShenZhen Andonstar Technology Co.,Ltd.','shenzhen-andonstar-technology-co-ltd','active',NOW(),NOW()),
('JUMO','jumo','active',NOW(),NOW()),
('NUMTEC INTERSTAHL ANLAGENBAU GMBH','numtec-interstahl-anlagenbau-gmbh','active',NOW(),NOW()),
('VELAN INC.','velan-inc','active',NOW(),NOW()),
('VOGELSANG INDIA PVT LTD','vogelsang-india-pvt-ltd','active',NOW(),NOW()),
('COSTACURTA SPA','costacurta-spa','active',NOW(),NOW()),
('Grundfos','grundfos','active',NOW(),NOW()),
('Westerstrand','westerstrand','active',NOW(),NOW()),
('ATELIERS BUSCH S.A.','ateliers-busch-s-a','active',NOW(),NOW()),
('Daikin','daikin','active',NOW(),NOW()),
('Axson','axson','active',NOW(),NOW()),
('Loctite','loctite','active',NOW(),NOW()),
('SANDVIK ROXON','sandvik-roxon','active',NOW(),NOW()),
('Bray','bray','active',NOW(),NOW()),
('INTERNATIONAL BALER CORPORRATION','international-baler-corporration','active',NOW(),NOW()),
('CRYOTHERM','cryotherm','active',NOW(),NOW()),
('VEGAFLEX','vegaflex','active',NOW(),NOW()),
('Frigotermica','frigotermica','active',NOW(),NOW()),
('SECO','seco','active',NOW(),NOW()),
('York, Johnson Control, Unit','york-johnson-control-unit','active',NOW(),NOW()),
('polytron','polytron','active',NOW(),NOW()),
('FATI','fati','active',NOW(),NOW()),
('NUOVO PIGNONE SPAOEM','nuovo-pignone-spaoem','active',NOW(),NOW()),
('FILVATEC ENGENIEROS S.A. SPAIN','filvatec-engenieros-s-a-spain','active',NOW(),NOW()),
('Vertiv','vertiv','active',NOW(),NOW()),
('Osborn GMBH','osborn-gmbh','active',NOW(),NOW()),
('AMCS TOTAL ANALYTIC SPECIALISTS','amcs-total-analytic-specialists','active',NOW(),NOW()),
('Omni flow Computers','omni-flow-computers','active',NOW(),NOW()),
('P&F','p-f','active',NOW(),NOW()),
('HIMA Paul Hildebrandt GmbH','hima-paul-hildebrandt-gmbh','active',NOW(),NOW()),
('Compair','compair','active',NOW(),NOW()),
('Gent By honeywell','gent-by-honeywell','active',NOW(),NOW()),
('Kitz Europe Gmbh','kitz-europe-gmbh','active',NOW(),NOW()),
('Avantor Sciences - VWR','avantor-sciences-vwr','active',NOW(),NOW()),
('Klinger UK','klinger-uk','active',NOW(),NOW()),
('Gestra UK Ltd','gestra-uk-ltd','active',NOW(),NOW()),
('Mechatherm International Ltd','mechatherm-international-ltd','active',NOW(),NOW()),
('FINDER POMPE Gruppo Aturia S.p.A.','finder-pompe-gruppo-aturia-s-p-a','active',NOW(),NOW()),
('Hanny reels','hanny-reels','active',NOW(),NOW()),
('IFM ELECTRONICS','ifm-electronics','active',NOW(),NOW()),
('Busch (UK) Ltd','busch-uk-ltd','active',NOW(),NOW()),
('GE Fanuc','ge-fanuc','active',NOW(),NOW()),
('CRANE','crane','active',NOW(),NOW()),
('BUHLER TECHNOLOGIES GERMANY','buhler-technologies-germany','active',NOW(),NOW()),
('Bosch and rexroth','bosch-and-rexroth','active',NOW(),NOW()),
('DEMAG CRANES & COMPONENTS GMBH.','demag-cranes-components-gmbh','active',NOW(),NOW()),
('PECORA CORPORATION','pecora-corporation','active',NOW(),NOW()),
('Humiseal','humiseal','active',NOW(),NOW()),
('Aerosol Locitite','aerosol-locitite','active',NOW(),NOW()),
('Dow corning','dow-corning','active',NOW(),NOW()),
('Kyner / Sky ler','kyner-sky-ler','active',NOW(),NOW()),
('Diamond Power','diamond-power','active',NOW(),NOW()),
('Topworx','topworx','active',NOW(),NOW()),
('Balluff Ltd','balluff-ltd','active',NOW(),NOW()),
('AMOT','amot','active',NOW(),NOW()),
('VULCANIC TERMOELECTRICA','vulcanic-termoelectrica','active',NOW(),NOW()),
('MAUS ITALIA','maus-italia','active',NOW(),NOW()),
('BARTON FIRTOP','barton-firtop','active',NOW(),NOW()),
('Powerite Division of Kinetrol Ltd.','powerite-division-of-kinetrol-ltd','active',NOW(),NOW()),
('hepa','hepa','active',NOW(),NOW()),
('GRANDETOP','grandetop','active',NOW(),NOW()),
('EDWARDS','edwards','active',NOW(),NOW()),
('BTT','btt','active',NOW(),NOW()),
('Tespro Electronics Corporation','tespro-electronics-corporation','active',NOW(),NOW()),
('Dron & Dickson Ltd','dron-dickson-ltd','active',NOW(),NOW()),
('Termochimica Impianti','termochimica-impianti','active',NOW(),NOW()),
('pelletroneurope GmbH','pelletroneurope-gmbh','active',NOW(),NOW()),
('GilAir-Plus','gilair-plus','active',NOW(),NOW()),
('Macher Distribution Limited','macher-distribution-limited','active',NOW(),NOW()),
('Alco X','alco-x','active',NOW(),NOW()),
('ALCO C','alco-c','active',NOW(),NOW()),
('bondorite','bondorite','active',NOW(),NOW()),
('Kempston Controls','kempston-controls','active',NOW(),NOW()),
('Terry Ferraris & C','terry-ferraris-c','active',NOW(),NOW()),
('INTORQ GMBH & CO. KG','intorq-gmbh-co-kg','active',NOW(),NOW()),
('IBAITOR','ibaitor','active',NOW(),NOW()),
('MAB','mab','active',NOW(),NOW()),
('AIR TECHNIC','air-technic','active',NOW(),NOW()),
('GE PANAMETRICS','ge-panametrics','active',NOW(),NOW()),
('NIPPON ACCUMULATOR CO LTD','nippon-accumulator-co-ltd','active',NOW(),NOW()),
('RENK','renk','active',NOW(),NOW()),
('DOMGAS INTERNATIONAL / SCORE VAC LIMITED','domgas-international-score-vac-limited','active',NOW(),NOW()),
('ATB RIVA CALZONI','atb-riva-calzoni','active',NOW(),NOW()),
('WATCON B.V.','watcon-b-v','active',NOW(),NOW()),
('LLORPIC VENTILADORES SA','llorpic-ventiladores-sa','active',NOW(),NOW()),
('FUNKE WARMEAUSTAUSCHER APPARATEBAU','funke-warmeaustauscher-apparatebau','active',NOW(),NOW()),
('HONOR PUMP USA','honor-pump-usa','active',NOW(),NOW()),
('NEUTRALIZER PRODUCT COALESCER','neutralizer-product-coalescer','active',NOW(),NOW()),
('AMACS PROCESS TOWER INTERNALS','amacs-process-tower-internals','active',NOW(),NOW()),
('Viking Supply Net Ltd','viking-supply-net-ltd','active',NOW(),NOW()),
('SEW EURODRIVE','sew-eurodrive','active',NOW(),NOW()),
('DICKOW','dickow','active',NOW(),NOW()),
('THERMO ELECTRA','thermo-electra','active',NOW(),NOW()),
('FIMET','fimet','active',NOW(),NOW()),
('APB APPARATEBAU SCHWEISSTECHNIK GMBH','apb-apparatebau-schweisstechnik-gmbh','active',NOW(),NOW()),
('NICSA','nicsa','active',NOW(),NOW()),
('MACCHI','macchi','active',NOW(),NOW()),
('THOMAS RESEARCH PRODUCTS','thomas-research-products','active',NOW(),NOW()),
('STOLWAY','stolway','active',NOW(),NOW()),
('YUASA','yuasa','active',NOW(),NOW()),
('DAFRAM S.P.A.','dafram-s-p-a','active',NOW(),NOW()),
('GO','go','active',NOW(),NOW()),
('PARAGON SCIENTIFIC','paragon-scientific','active',NOW(),NOW()),
('Maxseal','maxseal','active',NOW(),NOW()),
('METRON','metron','active',NOW(),NOW()),
('BAR GMBH','bar-gmbh','active',NOW(),NOW()),
('PURE AIR FILTRATION LLC','pure-air-filtration-llc','active',NOW(),NOW()),
('DONALDSON','donaldson','active',NOW(),NOW()),
('Henkel Loctite','henkel-loctite','active',NOW(),NOW()),
('Rosenberger','rosenberger','active',NOW(),NOW()),
('Telegartner','telegartner','active',NOW(),NOW()),
('FANUC CORPORATION','fanuc-corporation','active',NOW(),NOW()),
('Vaitor','vaitor','active',NOW(),NOW()),
('SPIRAX SARCO SRL','spirax-sarco-srl','active',NOW(),NOW()),
('BIRDWELL COMPANY, THE US','birdwell-company-the-us','active',NOW(),NOW()),
('HAMMORTHY ENGINEERING LIMITED','hammorthy-engineering-limited','active',NOW(),NOW()),
('GUNNEBO WEGO GMBH','gunnebo-wego-gmbh','active',NOW(),NOW()),
('ALLWELLER / MYCOM','allweller-mycom','active',NOW(),NOW()),
('KUETTNER','kuettner','active',NOW(),NOW()),
('MOOG','moog','active',NOW(),NOW()),
('APT SECURITY SYSTEMS','apt-security-systems','active',NOW(),NOW()),
('Heidenhain','heidenhain','active',NOW(),NOW()),
('THE JAPAN STEEL WORKS, LTD.','the-japan-steel-works-ltd','active',NOW(),NOW()),
('CLARK-RELIANCE CORP.','clark-reliance-corp','active',NOW(),NOW()),
('THOMASSEN COMPRESSION SYSTEMS','thomassen-compression-systems','active',NOW(),NOW()),
('J.H. FENNER AND CO LTD GB','j-h-fenner-and-co-ltd-gb','active',NOW(),NOW()),
('Delta Neu','delta-neu','active',NOW(),NOW()),
('PARKER HANNIFIN','parker-hannifin','active',NOW(),NOW()),
('KUHN & KAISER GMBH','kuhn-kaiser-gmbh','active',NOW(),NOW()),
('HOLDPEAK','holdpeak','active',NOW(),NOW()),
('SIMCO ENGINEERS LTD','simco-engineers-ltd','active',NOW(),NOW()),
('SOLER & PALAU','soler-palau','active',NOW(),NOW()),
('LOCCIONI-GENERAL IMPIANTI SRL, ITALY','loccioni-general-impianti-srl-italy','active',NOW(),NOW()),
('M.COULTHARD & CO LTD.','m-coulthard-co-ltd','active',NOW(),NOW()),
('ICE-INTERNATIONAL COMBUSTION EQUIPMENT','ice-international-combustion-equipment','active',NOW(),NOW()),
('LMF','lmf','active',NOW(),NOW()),
('CAMERON WKM','cameron-wkm','active',NOW(),NOW()),
('\"AA TECHNISCHE DIENSTE AB SICHERHEIT UND\"','aa-technische-dienste-ab-sicherheit-und','active',NOW(),NOW()),
('HOMA Pumpenfabrik GmbH','homa-pumpenfabrik-gmbh','active',NOW(),NOW()),
('FOXBORO ECKARDT GMBH','foxboro-eckardt-gmbh','active',NOW(),NOW()),
('HIDRACAR SA','hidracar-sa','active',NOW(),NOW()),
('ESI Technologies Group','esi-technologies-group','active',NOW(),NOW()),
('PLASSER','plasser','active',NOW(),NOW()),
('DOVIANUS BV, NETHERLANDS','dovianus-bv-netherlands','active',NOW(),NOW()),
('FISHER EMERSON PROCESS MANAGEMENT','fisher-emerson-process-management','active',NOW(),NOW()),
('Vee Bee Filtration UK Ltd','vee-bee-filtration-uk-ltd','active',NOW(),NOW()),
('ESMIL WATER  SYSTEMS','esmil-water-systems','active',NOW(),NOW()),
('OMEGA','omega','active',NOW(),NOW()),
('ECOMACCHINE SPA','ecomacchine-spa','active',NOW(),NOW()),
('Fischer Scientific','fischer-scientific','active',NOW(),NOW()),
('Across','across','active',NOW(),NOW()),
('Merck Millipore KGaA','merck-millipore-kgaa','active',NOW(),NOW()),
('Panreac','panreac','active',NOW(),NOW()),
('MOELLER','moeller','active',NOW(),NOW()),
('Solinas Benelux BV','solinas-benelux-bv','active',NOW(),NOW()),
('BW gas detectors','bw-gas-detectors','active',NOW(),NOW()),
('Elementor','elementor','active',NOW(),NOW()),
('Tanaka','tanaka','active',NOW(),NOW()),
('ALVARADO MANUFACTURING COMPANY, INC.','alvarado-manufacturing-company-inc','active',NOW(),NOW()),
('PREMABERGO ITALIANA SRL','premabergo-italiana-srl','active',NOW(),NOW()),
('BOURDON HAENNI','bourdon-haenni','active',NOW(),NOW()),
('MSC','msc','active',NOW(),NOW()),
('STAHL SCHWEIZ AG','stahl-schweiz-ag','active',NOW(),NOW()),
('VAN GEEL LEGRAND','van-geel-legrand','active',NOW(),NOW()),
('PHILIPS LIGHTING BV','philips-lighting-bv','active',NOW(),NOW()),
('TRANSLAMP LTD','translamp-ltd','active',NOW(),NOW()),
('ABB BV BU INSTRUMENTATION','abb-bv-bu-instrumentation','active',NOW(),NOW()),
('ABB TANDD SPA','abb-tandd-spa','active',NOW(),NOW()),
('GUTOR ELECTRONIC LLC','gutor-electronic-llc','active',NOW(),NOW()),
('INGERSOLL DRESSER SALES CO','ingersoll-dresser-sales-co','active',NOW(),NOW()),
('ROLLS-ROYCE POWER ENGINEERING PLC','rolls-royce-power-engineering-plc','active',NOW(),NOW()),
('Flexbar','flexbar','active',NOW(),NOW()),
('Toyoseiki','toyoseiki','active',NOW(),NOW()),
('Matsunami','matsunami','active',NOW(),NOW()),
('Panalytical','panalytical','active',NOW(),NOW()),
('Titanium','titanium','active',NOW(),NOW()),
('PAUL POLLRICH GMBH AND COMP.','paul-pollrich-gmbh-and-comp','active',NOW(),NOW()),
('HARRIS CALORIFIC SRL IT','harris-calorific-srl-it','active',NOW(),NOW()),
('SIGMA','sigma','active',NOW(),NOW()),
('ASONE','asone','active',NOW(),NOW()),
('JOHNSON MATTHEY CATALYSTS','johnson-matthey-catalysts','active',NOW(),NOW()),
('EASY LASER','easy-laser','active',NOW(),NOW()),
('ARMSTRONG','armstrong','active',NOW(),NOW()),
('GEA LUFTKUHLER GMBH','gea-luftkuhler-gmbh','active',NOW(),NOW()),
('Teledyne,','teledyne','active',NOW(),NOW()),
('Cannon Instruments','cannon-instruments','active',NOW(),NOW()),
('North Sea Ventilation Co .','north-sea-ventilation-co','active',NOW(),NOW()),
('Shaw Meter','shaw-meter','active',NOW(),NOW()),
('TRANTER INTERNATIONAL AB','tranter-international-ab','active',NOW(),NOW()),
('KLINGER SPA','klinger-spa','active',NOW(),NOW()),
('BESA','besa','active',NOW(),NOW()),
('SEDINTA','sedinta','active',NOW(),NOW()),
('APIERRE SRL IT','apierre-srl-it','active',NOW(),NOW()),
('FACET ITALIANA SPA IT','facet-italiana-spa-it','active',NOW(),NOW()),
('DETTIN','dettin','active',NOW(),NOW()),
('Fixturlaser UK Ltd','fixturlaser-uk-ltd','active',NOW(),NOW()),
('Azcue','azcue','active',NOW(),NOW()),
('Ingressoll Rand','ingressoll-rand','active',NOW(),NOW()),
('GMP S.p.A.','gmp-s-p-a','active',NOW(),NOW()),
('NSK Bearings','nsk-bearings','active',NOW(),NOW()),
('Woodward','woodward','active',NOW(),NOW()),
('McMaster-Carr','mcmaster-carr','active',NOW(),NOW()),
('HAZMAT','hazmat','active',NOW(),NOW()),
('Chalmit','chalmit','active',NOW(),NOW()),
('Kyoto Electronics','kyoto-electronics','active',NOW(),NOW()),
('Regal Beloit/Marathon Electric','regal-beloit-marathon-electric','active',NOW(),NOW()),
('PAC/AC ANALYTICAL CONTROLS','pac-ac-analytical-controls','active',NOW(),NOW()),
('PALMERWAHL, USA','palmerwahl-usa','active',NOW(),NOW()),
('Muromoto Tekko co., Ltd','muromoto-tekko-co-ltd','active',NOW(),NOW()),
('Kurita Europe GmbH','kurita-europe-gmbh','active',NOW(),NOW()),
('GE INDUSTRIAL SYSTEMS','ge-industrial-systems','active',NOW(),NOW()),
('Thermo Fisher Scientific','thermo-fisher-scientific','active',NOW(),NOW()),
('TOA-DKK','toa-dkk','active',NOW(),NOW()),
('MONITOR TECHNOLOGIES','monitor-technologies','active',NOW(),NOW()),
('AMETEK Lands instruments','ametek-lands-instruments','active',NOW(),NOW()),
('TDK-Lambda','tdk-lambda','active',NOW(),NOW()),
('KILLARK','killark','active',NOW(),NOW()),
('Taylor','taylor','active',NOW(),NOW()),
('Thermo Scientific','thermo-scientific','active',NOW(),NOW()),
('Agilent','agilent','active',NOW(),NOW()),
('Brenntag UK','brenntag-uk','active',NOW(),NOW()),
('Ventilux','ventilux','active',NOW(),NOW()),
('DIONEX','dionex','active',NOW(),NOW()),
('Vaccu brand','vaccu-brand','active',NOW(),NOW()),
('LEWA Gmbh','lewa-gmbh','active',NOW(),NOW()),
('Jensen Tools','jensen-tools','active',NOW(),NOW()),
('STANLEY TOOLS','stanley-tools','active',NOW(),NOW()),
('CONTINENTAL','continental','active',NOW(),NOW()),
('Intergen SRL','intergen-srl','active',NOW(),NOW()),
('PKP PROZESSMESSTECHNIK GMBH','pkp-prozessmesstechnik-gmbh','active',NOW(),NOW()),
('WARREN RUPP COMPANY','warren-rupp-company','active',NOW(),NOW()),
('TP Solutions','tp-solutions','active',NOW(),NOW()),
('Interactive Safety Products, Inc.','interactive-safety-products-inc','active',NOW(),NOW()),
('Blagdon Pump','blagdon-pump','active',NOW(),NOW()),
('X-Acto','x-acto','active',NOW(),NOW()),
('SOMERSET SOLDERS LTD','somerset-solders-ltd','active',NOW(),NOW()),
('STERITOOL','steritool','active',NOW(),NOW()),
('Glenair','glenair','active',NOW(),NOW()),
('Stahlwille','stahlwille','active',NOW(),NOW()),
('Aim Tti','aim-tti','active',NOW(),NOW()),
('BALDOR','baldor','active',NOW(),NOW()),
('AVX','avx','active',NOW(),NOW()),
('Erem by Weller','erem-by-weller','active',NOW(),NOW()),
('Broppe','broppe','active',NOW(),NOW()),
('Devcon','devcon','active',NOW(),NOW()),
('TEKTRONIX','tektronix','active',NOW(),NOW()),
('SDMO','sdmo','active',NOW(),NOW()),
('Promax','promax','active',NOW(),NOW()),
('HONEYWELL NORTH','honeywell-north','active',NOW(),NOW()),
('Norbar','norbar','active',NOW(),NOW()),
('Makita','makita','active',NOW(),NOW()),
('COBRA','cobra','active',NOW(),NOW()),
('Antistat','antistat','active',NOW(),NOW()),
('Wiha','wiha','active',NOW(),NOW()),
('Stanley-Proto','stanley-proto','active',NOW(),NOW()),
('Allparts','allparts','active',NOW(),NOW()),
('Bondhus','bondhus','active',NOW(),NOW()),
('Rock River','rock-river','active',NOW(),NOW()),
('TEKTON','tekton','active',NOW(),NOW()),
('Werkzeug','werkzeug','active',NOW(),NOW()),
('Myrra','myrra','active',NOW(),NOW()),
('Wera','wera','active',NOW(),NOW()),
('Dormer','dormer','active',NOW(),NOW()),
('DMC','dmc','active',NOW(),NOW()),
('Pritchard Photo Research','pritchard-photo-research','active',NOW(),NOW()),
('Xcelite','xcelite','active',NOW(),NOW()),
('MURR','murr','active',NOW(),NOW()),
('MITSUBISHI','mitsubishi','active',NOW(),NOW()),
('ANSELL','ansell','active',NOW(),NOW()),
('HENKE SASS WOLF','henke-sass-wolf','active',NOW(),NOW()),
('B BRAUN MELSUNGEN AG','b-braun-melsungen-ag','active',NOW(),NOW()),
('FULHAM','fulham','active',NOW(),NOW()),
('SPIRAX SARCO','spirax-sarco','active',NOW(),NOW()),
('VESDA VLF','vesda-vlf','active',NOW(),NOW()),
('BROOKS INSTRUMENT','brooks-instrument','active',NOW(),NOW()),
('THERMO RAMSEY ITALIA SRL','thermo-ramsey-italia-srl','active',NOW(),NOW()),
('SPECK POMPEN','speck-pompen','active',NOW(),NOW()),
('Metrix Instrument Company','metrix-instrument-company','active',NOW(),NOW()),
('REXROTH-AVENTICS','rexroth-aventics','active',NOW(),NOW()),
('WHEATON','wheaton','active',NOW(),NOW()),
('DAYTON','dayton','active',NOW(),NOW()),
('ITW SWITCHES','itw-switches','active',NOW(),NOW()),
('COOPER BUSSMANN','cooper-bussmann','active',NOW(),NOW()),
('RESTEK','restek','active',NOW(),NOW()),
('Connell','connell','active',NOW(),NOW()),
('Osram','osram','active',NOW(),NOW()),
('GENERAL ELECTRIC(GE)','general-electric-ge','active',NOW(),NOW()),
('Niton Equipment Ltd.','niton-equipment-ltd','active',NOW(),NOW()),
('PRUFTECHNIK','pruftechnik','active',NOW(),NOW()),
('CIGLOW','ciglow','active',NOW(),NOW()),
('SANYO DEKNI','sanyo-dekni','active',NOW(),NOW()),
('Slaters Electricals UK','slaters-electricals-uk','active',NOW(),NOW()),
('CI ANALYTICS','ci-analytics','active',NOW(),NOW()),
('SHELL','shell','active',NOW(),NOW()),
('HBL NiCad Batteries (UK) Ltd','hbl-nicad-batteries-uk-ltd','active',NOW(),NOW()),
('PULSARLUBE','pulsarlube','active',NOW(),NOW()),
('DEPA CRANE PROCESS FLOW TECHNOLOGIES GMBH','depa-crane-process-flow-technologies-gmbh','active',NOW(),NOW()),
('POMPE CUCCHI','pompe-cucchi','active',NOW(),NOW()),
('ELT','elt','active',NOW(),NOW()),
('WIKA','wika','active',NOW(),NOW()),
('MCDANIEL','mcdaniel','active',NOW(),NOW()),
('THERMON','thermon','active',NOW(),NOW()),
('VORTEC','vortec','active',NOW(),NOW()),
('TRACO POWER','traco-power','active',NOW(),NOW()),
('WESTCAR','westcar','active',NOW(),NOW()),
('MILTON ROY EUROPE','milton-roy-europe','active',NOW(),NOW()),
('American AVK','american-avk','active',NOW(),NOW()),
('SIG Italy','sig-italy','active',NOW(),NOW()),
('WALTERS/Sioux Corporation','walters-sioux-corporation','active',NOW(),NOW()),
('HERZOG/PAC','herzog-pac','active',NOW(),NOW()),
('COPELAND','copeland','active',NOW(),NOW()),
('BASLER','basler','active',NOW(),NOW()),
('PHILIPS ADVANCE','philips-advance','active',NOW(),NOW()),
('CAMOZZI','camozzi','active',NOW(),NOW()),
('LENZE','lenze','active',NOW(),NOW()),
('SETA','seta','active',NOW(),NOW()),
('Home saver','home-saver','active',NOW(),NOW()),
('DOGA','doga','active',NOW(),NOW()),
('KIEPE ELEKTRIK','kiepe-elektrik','active',NOW(),NOW()),
('Eland Cables','eland-cables','active',NOW(),NOW()),
('DAUBERT CROMWELL','daubert-cromwell','active',NOW(),NOW()),
('MOYNO INC','moyno-inc','active',NOW(),NOW()),
('Atlanta','atlanta','active',NOW(),NOW()),
('Jonesco (Preston) Ltd','jonesco-preston-ltd','active',NOW(),NOW()),
('LabTech','labtech','active',NOW(),NOW()),
('NABERTHERM','nabertherm','active',NOW(),NOW()),
('DESMI','desmi','active',NOW(),NOW()),
('Tyco Ansul, U.S.A.','tyco-ansul-u-s-a','active',NOW(),NOW()),
('VEGA Controls Limited','vega-controls-limited','active',NOW(),NOW()),
('Glamox.','glamox','active',NOW(),NOW()),
('DETRONICS','detronics','active',NOW(),NOW()),
('Daniel Measurement and Control','daniel-measurement-and-control','active',NOW(),NOW()),
('Dawson Downie','dawson-downie','active',NOW(),NOW()),
('DELTA CONTROL','delta-control','active',NOW(),NOW()),
('DIGI INTERNATIONAL','digi-international','active',NOW(),NOW()),
('DOSAPRO MILTON','dosapro-milton','active',NOW(),NOW()),
('DAMEN SHIP','damen-ship','active',NOW(),NOW()),
('GOUDA REFRACTORIES B.V.','gouda-refractories-b-v','active',NOW(),NOW()),
('BEACON EXTENDER INC','beacon-extender-inc','active',NOW(),NOW()),
('MAGNETIC SENSOR CORPORATION','magnetic-sensor-corporation','active',NOW(),NOW()),
('ROYAL PURPLE','royal-purple','active',NOW(),NOW()),
('BARTEC BENKE GMBH','bartec-benke-gmbh','active',NOW(),NOW()),
('POWER SONIC','power-sonic','active',NOW(),NOW()),
('AEROMECCANICA STRANICH, ITALY','aeromeccanica-stranich-italy','active',NOW(),NOW()),
('Ludwig Schneider','ludwig-schneider','active',NOW(),NOW()),
('MINCO','minco','active',NOW(),NOW()),
('ATLAS COPCO','atlas-copco','active',NOW(),NOW()),
('WAUKESSHA','waukessha','active',NOW(),NOW()),
('HEX BRASS COOPER AND ALLOY LTD','hex-brass-cooper-and-alloy-ltd','active',NOW(),NOW()),
('Bosta UK Ltd.','bosta-uk-ltd','active',NOW(),NOW()),
('KOCHEK CO., INC','kochek-co-inc','active',NOW(),NOW()),
('Schiefer','schiefer','active',NOW(),NOW()),
('SIRACO','siraco','active',NOW(),NOW()),
('Jonesco Ltd.','jonesco-ltd','active',NOW(),NOW()),
('FISHER CONTROLS INTERNATIONAL','fisher-controls-international','active',NOW(),NOW()),
('CONACO SRL','conaco-srl','active',NOW(),NOW()),
('RUBYCON','rubycon','active',NOW(),NOW()),
('VISHAY BC COMPONENTS','vishay-bc-components','active',NOW(),NOW()),
('Littelfuse','littelfuse','active',NOW(),NOW()),
('3M','3m','active',NOW(),NOW()),
('DURAVAC','duravac','active',NOW(),NOW()),
('Alaris Antennas (Pty) Ltd','alaris-antennas-pty-ltd','active',NOW(),NOW()),
('MTL SURGE TECHNOLOGIES','mtl-surge-technologies','active',NOW(),NOW()),
('MULTICOMP','multicomp','active',NOW(),NOW()),
('WELWYN','welwyn','active',NOW(),NOW()),
('KEYS','keys','active',NOW(),NOW()),
('Martindale','martindale','active',NOW(),NOW()),
('Testmate','testmate','active',NOW(),NOW()),
('POWERCOM','powercom','active',NOW(),NOW()),
('Hakko','hakko','active',NOW(),NOW()),
('PANASONIC','panasonic','active',NOW(),NOW()),
('Motorola','motorola','active',NOW(),NOW()),
('FISNAR','fisnar','active',NOW(),NOW()),
('ELITE ENGINEERING LTD','elite-engineering-ltd','active',NOW(),NOW()),
('SEIKA','seika','active',NOW(),NOW()),
('PETER SWAN','peter-swan','active',NOW(),NOW()),
('LEC','lec','active',NOW(),NOW()),
('ZHONGDI','zhongdi','active',NOW(),NOW()),
('uxcell','uxcell','active',NOW(),NOW()),
('Stanley','stanley','active',NOW(),NOW()),
('FACOM','facom','active',NOW(),NOW()),
('EKLIND','eklind','active',NOW(),NOW()),
('COOPER TOOLS APEX OPERATION','cooper-tools-apex-operation','active',NOW(),NOW()),
('Sturtevant Richmont','sturtevant-richmont','active',NOW(),NOW()),
('Craftsman','craftsman','active',NOW(),NOW()),
('Klein Tools','klein-tools','active',NOW(),NOW()),
('Keysight Technologies','keysight-technologies','active',NOW(),NOW()),
('Bahco','bahco','active',NOW(),NOW()),
('RS Pro','rs-pro','active',NOW(),NOW()),
('Starrett','starrett','active',NOW(),NOW()),
('Rhopoint','rhopoint','active',NOW(),NOW()),
('Nordson Asymtek','nordson-asymtek','active',NOW(),NOW()),
('Jackson Professional Tools','jackson-professional-tools','active',NOW(),NOW()),
('PROTO','proto','active',NOW(),NOW()),
('HARWIN','harwin','active',NOW(),NOW()),
('Elpress','elpress','active',NOW(),NOW()),
('Oakton','oakton','active',NOW(),NOW()),
('HIOS/Mountz, Inc','hios-mountz-inc','active',NOW(),NOW()),
('Solberg International','solberg-international','active',NOW(),NOW()),
('GEDORE','gedore','active',NOW(),NOW()),
('DATEL','datel','active',NOW(),NOW()),
('Bega Special Tools','bega-special-tools','active',NOW(),NOW()),
('OHMART/VEGA CORP','ohmart-vega-corp','active',NOW(),NOW()),
('Advanced Energy Industries GmbH','advanced-energy-industries-gmbh','active',NOW(),NOW()),
('STL International Ltd','stl-international-ltd','active',NOW(),NOW()),
('GATES CORPORATION','gates-corporation','active',NOW(),NOW()),
('MARSH BELLOFRAM','marsh-bellofram','active',NOW(),NOW()),
('BRAN LUEBBE GMBH','bran-luebbe-gmbh','active',NOW(),NOW()),
('COSEL','cosel','active',NOW(),NOW()),
('ELOBAU SENSOR TECHNOLOGY','elobau-sensor-technology','active',NOW(),NOW()),
('OMC SRL ITALY','omc-srl-italy','active',NOW(),NOW()),
('VIKING CORPORATION','viking-corporation','active',NOW(),NOW()),
('Industronic GMBH','industronic-gmbh','active',NOW(),NOW()),
('Protecno SRL','protecno-srl','active',NOW(),NOW()),
('GEWISS','gewiss','active',NOW(),NOW()),
('MEGGER','megger','active',NOW(),NOW()),
('HOMAS RESEARCH PRODUCTS','homas-research-products','active',NOW(),NOW()),
('HIRSCHMANN','hirschmann','active',NOW(),NOW()),
('NORTRONICS','nortronics','active',NOW(),NOW()),
('CAMERON','cameron','active',NOW(),NOW()),
('QUALITY HYDRAULIC POWER LTD','quality-hydraulic-power-ltd','active',NOW(),NOW()),
('BOLDROCCHI','boldrocchi','active',NOW(),NOW()),
('PHD POWER','phd-power','active',NOW(),NOW()),
('TALISMAN SECURITY PRODUCTS','talisman-security-products','active',NOW(),NOW()),
('INSTRUMENT TRANSFORMER INC','instrument-transformer-inc','active',NOW(),NOW()),
('MOLEX','molex','active',NOW(),NOW()),
('PERKIN ELMER','perkin-elmer','active',NOW(),NOW()),
('ANTON PARR','anton-parr','active',NOW(),NOW()),
('TESA','tesa','active',NOW(),NOW()),
('K-FACTOR SRL','k-factor-srl','active',NOW(),NOW()),
('HANNAY REELS','hannay-reels','active',NOW(),NOW()),
('RS','rs','active',NOW(),NOW()),
('CORTEM SPA, ITALY','cortem-spa-italy','active',NOW(),NOW()),
('POULTEN SELFE & LEE','poulten-selfe-lee','active',NOW(),NOW()),
('AMELEC','amelec','active',NOW(),NOW()),
('JCT Analysentechnik GmbH','jct-analysentechnik-gmbh','active',NOW(),NOW()),
('AX-AIR-FANS','ax-air-fans','active',NOW(),NOW()),
('EATON','eaton','active',NOW(),NOW()),
('Gali Compressors','gali-compressors','active',NOW(),NOW()),
('METTLER TOLEDO','mettler-toledo','active',NOW(),NOW()),
('VWR','vwr','active',NOW(),NOW()),
('Central Machinery','central-machinery','active',NOW(),NOW()),
('Wilton','wilton','active',NOW(),NOW()),
('ETS','ets','active',NOW(),NOW()),
('Cembre','cembre','active',NOW(),NOW()),
('Husky','husky','active',NOW(),NOW()),
('Clarke','clarke','active',NOW(),NOW()),
('LUTZ GmbH & Co. KG.','lutz-gmbh-co-kg','active',NOW(),NOW()),
('SAINT-GOBAIN NORPRO','saint-gobain-norpro','active',NOW(),NOW()),
('Servomex','servomex','active',NOW(),NOW()),
('EXTECH INSTRUMENT','extech-instrument','active',NOW(),NOW()),
('Netter Vibration','netter-vibration','active',NOW(),NOW()),
('DOPAK','dopak','active',NOW(),NOW()),
('HACH LANGE LTD','hach-lange-ltd','active',NOW(),NOW()),
('Acros Organics','acros-organics','active',NOW(),NOW()),
('Alvarado Mfg. Co., Inc.','alvarado-mfg-co-inc','active',NOW(),NOW()),
('Drger','drger','active',NOW(),NOW()),
('PhyMetrix, Inc','phymetrix-inc','active',NOW(),NOW()),
('FLIR','flir','active',NOW(),NOW()),
('SYSTECH INSTRUMENTS LIMITED','systech-instruments-limited','active',NOW(),NOW()),
('Raesystems','raesystems','active',NOW(),NOW()),
('BIS PROZESSTECHNIK GMBH','bis-prozesstechnik-gmbh','active',NOW(),NOW()),
('Litre Meter Ltd','litre-meter-ltd','active',NOW(),NOW()),
('PLUS','plus','active',NOW(),NOW()),
('Dry tech, Inc','dry-tech-inc','active',NOW(),NOW()),
('CRANE PUMP INC','crane-pump-inc','active',NOW(),NOW()),
('Ametek Process Instruments','ametek-process-instruments','active',NOW(),NOW()),
('SAAB ROSEMOUNT','saab-rosemount','active',NOW(),NOW()),
('North Sea Ventilation Co. UK','north-sea-ventilation-co-uk','active',NOW(),NOW()),
('BOPP & REUTHER MESSTECHNIK GMBH','bopp-reuther-messtechnik-gmbh','active',NOW(),NOW()),
('BOPP & REUTHER MESSTECHNIK GMBH','bopp-reuther-messtechnik-gmbh','active',NOW(),NOW()),
('Shaw Moisture Meters (UK) Ltd','shaw-moisture-meters-uk-ltd','active',NOW(),NOW()),
('Magnetrol International UK','magnetrol-international-uk','active',NOW(),NOW()),
('PMV','pmv','active',NOW(),NOW()),
('IME SPA IT','ime-spa-it','active',NOW(),NOW()),
('PENN Johnson Controls','penn-johnson-controls','active',NOW(),NOW()),
('JANSENS & DIEPERINK B.V.','jansens-dieperink-b-v','active',NOW(),NOW()),
('ALRE, LT REGELTECHNIK GMBH','alre-lt-regeltechnik-gmbh','active',NOW(),NOW()),
('SAPAG','sapag','active',NOW(),NOW()),
('Arco','arco','active',NOW(),NOW()),
('FAIRCHILD','fairchild','active',NOW(),NOW()),
('Texas Instruments','texas-instruments','active',NOW(),NOW()),
('TECNO VIBRAZIONI VENANZETTI/ ROSTA AB','tecno-vibrazioni-venanzetti-rosta-ab','active',NOW(),NOW()),
('NORGREN','norgren','active',NOW(),NOW()),
('WEST CONTROL SOLUTIONS','west-control-solutions','active',NOW(),NOW()),
('HW Group, S.R.O','hw-group-s-r-o','active',NOW(),NOW()),
('ZUCCHETTI SRL','zucchetti-srl','active',NOW(),NOW()),
('ASCO POMPE / FYBROC','asco-pompe-fybroc','active',NOW(),NOW()),
('MAMPAEY OFFSHORE INDUSTRIES BV','mampaey-offshore-industries-bv','active',NOW(),NOW()),
('R Stahl','r-stahl','active',NOW(),NOW()),
('Scott Safety (A Tyco international Company).','scott-safety-a-tyco-international-company','active',NOW(),NOW()),
('THERMO ELECTRIC','thermo-electric','active',NOW(),NOW()),
('Mag-Lite','mag-lite','active',NOW(),NOW()),
('Cl Analytics','cl-analytics','active',NOW(),NOW()),
('MHT','mht','active',NOW(),NOW()),
('ALSTON SYSTEMS','alston-systems','active',NOW(),NOW()),
('SAMSON CONTROLS LTD','samson-controls-ltd','active',NOW(),NOW()),
('IME ISTRUM','ime-istrum','active',NOW(),NOW()),
('ALLEN-BRADLEY','allen-bradley','active',NOW(),NOW()),
('cole parmer','cole-parmer','active',NOW(),NOW()),
('TYCO THERMAL CONTROLS','tyco-thermal-controls','active',NOW(),NOW()),
('SPX PROCESS EQUIPMENT GB','spx-process-equipment-gb','active',NOW(),NOW()),
('APT Controls Ltd','apt-controls-ltd','active',NOW(),NOW()),
('Jacoby-Tar box','jacoby-tar-box','active',NOW(),NOW()),
('FERRAZ SHAWMUT US','ferraz-shawmut-us','active',NOW(),NOW()),
('OMRON CORP','omron-corp','active',NOW(),NOW()),
('PGI INTERNATIONAL','pgi-international','active',NOW(),NOW()),
('Hatlapa GmbH & Co. KG','hatlapa-gmbh-co-kg','active',NOW(),NOW()),
('GENERAL MONITORS SYSTEMS','general-monitors-systems','active',NOW(),NOW()),
('MONO PUMPS LTD GB','mono-pumps-ltd-gb','active',NOW(),NOW()),
('MEDC','medc','active',NOW(),NOW()),
('FLOWSERVE','flowserve','active',NOW(),NOW()),
('FARRIS','farris','active',NOW(),NOW()),
('Cla-Val UK Ltd','cla-val-uk-ltd','active',NOW(),NOW()),
('DANFOSS','danfoss','active',NOW(),NOW()),
('ROUSEMOUNT','rousemount','active',NOW(),NOW()),
('SIGMA-ALDRICH','sigma-aldrich','active',NOW(),NOW()),
('SYSTECH INSTRUMENTS LIMITED','systech-instruments-limited','active',NOW(),NOW()),
('PELCO','pelco','active',NOW(),NOW()),
('SMC CORPORATION','smc-corporation','active',NOW(),NOW()),
('Leser','leser','active',NOW(),NOW()),
('ABB','abb','active',NOW(),NOW()),
('PHILIPS OR EQUIVALENT','philips-or-equivalent','active',NOW(),NOW()),
('DELTA SCIENTIFIC CORPORATION','delta-scientific-corporation','active',NOW(),NOW()),
('Wrtsil Water Systems Ltd','wrtsil-water-systems-ltd','active',NOW(),NOW()),
('ENSPEC POWER LTD','enspec-power-ltd','active',NOW(),NOW()),
('MUNTERS CORPORATION','munters-corporation','active',NOW(),NOW()),
('FESTO','festo','active',NOW(),NOW()),
('SAFT POWER SYSTEMS','saft-power-systems','active',NOW(),NOW()),
('ALLESSACHEMIE','allessachemie','active',NOW(),NOW()),
('WOUTER WITZEL EUROVALVE','wouter-witzel-eurovalve','active',NOW(),NOW()),
('ORBITEC','orbitec','active',NOW(),NOW()),
('PHOENIX','phoenix','active',NOW(),NOW()),
('PHOENIX CONTACT','phoenix-contact','active',NOW(),NOW()),
('ANSALDO SISTEMI INDUSTRIALI,SPA','ansaldo-sistemi-industriali-spa','active',NOW(),NOW()),
('TAPCOENPRO INTERNATIONAL','tapcoenpro-international','active',NOW(),NOW()),
('ALFA VALVOLE','alfa-valvole','active',NOW(),NOW()),
('CONDOR TECHNOLOGY LTD.','condor-technology-ltd','active',NOW(),NOW()),
('AUTOFLOW','autoflow','active',NOW(),NOW()),
('EMTROL LLC, USA','emtrol-llc-usa','active',NOW(),NOW()),
('Honeywell / BW Technologies','honeywell-bw-technologies','active',NOW(),NOW()),
('DOUGLAS CHERO','douglas-chero','active',NOW(),NOW()),
('RITTAL','rittal','active',NOW(),NOW()),
('GEA BATIGNOLLES TECH THERMIQUES','gea-batignolles-tech-thermiques','active',NOW(),NOW()),
('EMERSON PROCESS MANAGEMENT LTD','emerson-process-management-ltd','active',NOW(),NOW()),
('Kriwan Industrie Elektronik Gmbh','kriwan-industrie-elektronik-gmbh','active',NOW(),NOW()),
('Viconics Electronics Inc.','viconics-electronics-inc','active',NOW(),NOW()),
('PEPPERL + FUCHS','pepperl-fuchs','active',NOW(),NOW()),
('NASATKA BARRIER. INC (U.S.A)','nasatka-barrier-inc-u-s-a','active',NOW(),NOW()),
('INDUSTRIAL SCIENTIFIC CORPORATION','industrial-scientific-corporation','active',NOW(),NOW()),
('POLYCO,MODEL-BUTOCHEM','polyco-model-butochem','active',NOW(),NOW()),
('TOTAL FIRE GROUP US/ MORNING PRIDE','total-fire-group-us-morning-pride','active',NOW(),NOW()),
('HYDRAFIL','hydrafil','active',NOW(),NOW()),
('WALTER HERZOG GMBH','walter-herzog-gmbh','active',NOW(),NOW()),
('GRAINGER','grainger','active',NOW(),NOW()),
('CHERO PIPING','chero-piping','active',NOW(),NOW()),
('VARTA','varta','active',NOW(),NOW()),
('SAMEC SPA','samec-spa','active',NOW(),NOW()),
('IFE SRL','ife-srl','active',NOW(),NOW()),
('ANGELANTONI INDUSTRIES','angelantoni-industries','active',NOW(),NOW()),
('MILLIPORE CORPORATION US.','millipore-corporation-us','active',NOW(),NOW()),
('GEABATIGNOLLES TECH THERMIQUES','geabatignolles-tech-thermiques','active',NOW(),NOW()),
('PERRIN GMBH','perrin-gmbh','active',NOW(),NOW()),
('IDEC CORP','idec-corp','active',NOW(),NOW()),
('MARTIN MERKEL GMBH AND CO. KG DE','martin-merkel-gmbh-and-co-kg-de','active',NOW(),NOW()),
('TE Connectivity / Axicom','te-connectivity-axicom','active',NOW(),NOW()),
('Slovakia','slovakia','active',NOW(),NOW()),
('SIEMENS BUILDING TECHNOLOGIES','siemens-building-technologies','active',NOW(),NOW()),
('ELECTROMACH','electromach','active',NOW(),NOW()),
('BRUSH ELECTRICAL MACHINES LTD','brush-electrical-machines-ltd','active',NOW(),NOW()),
('ATEC SRL','atec-srl','active',NOW(),NOW()),
('ZIBAGA','zibaga','active',NOW(),NOW()),
('MANEUROP','maneurop','active',NOW(),NOW()),
('NUOVA FIMA SPA','nuova-fima-spa','active',NOW(),NOW()),
('GTC ITALIA SRL/ KTM VALVES','gtc-italia-srl-ktm-valves','active',NOW(),NOW()),
('DEEP SEA ELECTRONICS','deep-sea-electronics','active',NOW(),NOW()),
('FIAMM SPA','fiamm-spa','active',NOW(),NOW()),
('PISTER KUGELHAHNE','pister-kugelhahne','active',NOW(),NOW()),
('EUROPEX','europex','active',NOW(),NOW()),
('BONNEY FORGE SPA, ITALY','bonney-forge-spa-italy','active',NOW(),NOW()),
('MICHELL INSTRUMENTS','michell-instruments','active',NOW(),NOW()),
('TYCO VALVES AND CONTROLS AB DISTRIBUTION','tyco-valves-and-controls-ab-distribution','active',NOW(),NOW()),
('KABA Ltd','kaba-ltd','active',NOW(),NOW()),
('SCHENCK PROCESS GMBH','schenck-process-gmbh','active',NOW(),NOW()),
('PRODUCTOS PLASTICOS ANTICORROS','productos-plasticos-anticorros','active',NOW(),NOW()),
('GEORG FISCHER CENTRAL PLASTICS LLC','georg-fischer-central-plastics-llc','active',NOW(),NOW()),
('HERMETIC','hermetic','active',NOW(),NOW()),
('SBS STEEL BELT SYSTEMS SRL','sbs-steel-belt-systems-srl','active',NOW(),NOW()),
('ATB RIVACALZONI SPA','atb-rivacalzoni-spa','active',NOW(),NOW()),
('SKF','skf','active',NOW(),NOW()),
('TMEIC','tmeic','active',NOW(),NOW()),
('IGUS GMBH','igus-gmbh','active',NOW(),NOW()),
('GBM SRL','gbm-srl','active',NOW(),NOW()),
('AJ KOELLEMANN GMBH','aj-koellemann-gmbh','active',NOW(),NOW()),
('CROUSE HINDS ECM US COOPER INDUSTRIES INCORPORATED','crouse-hinds-ecm-us-cooper-industries-incorporated','active',NOW(),NOW()),
('PANDUIT','panduit','active',NOW(),NOW()),
('PARKER','parker','active',NOW(),NOW()),
('FOXBORO','foxboro','active',NOW(),NOW()),
('KROHNE','krohne','active',NOW(),NOW()),
('JOHN CRANE','john-crane','active',NOW(),NOW()),
('FLUKE','fluke','active',NOW(),NOW()),
('INGERSOLL RAND','ingersoll-rand','active',NOW(),NOW()),
('SIEMENS','siemens','active',NOW(),NOW()),
('SCHNEIDER','schneider','active',NOW(),NOW()),
('AIR TORQUE','air-torque','active',NOW(),NOW()),
('ZUCCHETTI','zucchetti','active',NOW(),NOW()),
('CURTISS-WRIGHT','curtiss-wright','active',NOW(),NOW());