<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New Quote Request</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f4f6f8; margin: 0; padding: 20px; color: #333; }
        .container { max-width: 650px; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #e0e0e0; margin: 0 auto; }
        .header { background: #0E3D2A; color: #ffffff; padding: 20px; text-align: center; border-radius: 6px 6px 0 0; }
        .header h2 { margin: 0; font-size: 22px; }
        .info-box { background: #F6F3EB; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #AD8036; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        table th, table td { padding: 10px 12px; border: 1px solid #ddd; text-align: left; font-size: 14px; }
        table th { background: #0E3D2A; color: #fff; }
        .footer { font-size: 12px; color: #777; margin-top: 25px; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Petchem Parts — New Quote Request</h2>
        </div>
        <p>A new quote request has been submitted on <strong>Petchem Parts</strong>.</p>
        
        <div class="info-box">
            <p><strong>Quote Ref:</strong> {{ $quoteRequest->quote_no }}</p>
            <p><strong>Customer Name:</strong> {{ $quoteRequest->name }}</p>
            <p><strong>Email:</strong> {{ $quoteRequest->email }}</p>
            <p><strong>Phone:</strong> {{ $quoteRequest->phone }}</p>
            @if($quoteRequest->company_name)
            <p><strong>Company:</strong> {{ $quoteRequest->company_name }}</p>
            @endif
            @if($quoteRequest->message)
            <p><strong>Message / Requirement:</strong> {{ $quoteRequest->message }}</p>
            @endif
        </div>

        <h3>Requested Items</h3>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Part No.</th>
                    <th>Model No.</th>
                    <th>Qty</th>
                </tr>
            </thead>
            <tbody>
                @foreach($quoteRequest->items as $item)
                <tr>
                    <td><strong>{{ $item->product_name }}</strong></td>
                    <td>{{ $item->part_number ?? 'N/A' }}</td>
                    <td>{{ $item->model_number ?? 'N/A' }}</td>
                    <td>{{ $item->quantity }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>This email was automatically generated by Petchem Parts System.</p>
        </div>
    </div>
</body>
</html>
